### PR TITLE
Update module.json for v11 compatibility

### PR DESCRIPTION
**Pull request by shun17**
Start migration for foundryvtt v11

### CODE REVIEW

**Comment by velara** [comment]
Have you tested this module  with the v11 dev branch? I’d rather not update the module.json files compatibility entry if the module itself isn’t compatible yet.

**Comment by shun17** [comment]
Not yet, I'll continue to see if other things are in need of migration for the update, then I'll update the pull request

**Comment by shun17** [comment]
Mmm, base module of pf2e has not yet been upgraded, ignore this pull request until further notice

**Comment by shun17** [comment]
I have just verified that with foundry v11.301.0 and pf2e 5.0.0-beta2 the module still works correctly. All functionality are the same.

**Comment by galaara98** [comment]
tested with v11, no noticeable issues.

**Pull request merged**
